package raft.stm;

public enum RaftEvent {
    BOOTSTRAP,
    HEARTBEAT_TIMEOUT,
    CANDIDATE_ELECTION_TIMEOUT,
    RECEIVE_VOTES_FROM_MAJORITY_SERVERS,
    DISCOVERY_CURRENT_LEADER,
    DISCOVERY_HIGH_TERM
}
